require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks! :linkage => :static

# workaround to avoid Xcode caching of Pods that requires
# temporary workaround, see https://github.com/CocoaPods/CocoaPods/issues/12226
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
end

target 'App' do
  capacitor_pods
end

pre_install do |installer|
  # CapacitorCommunityAdmob podspec sets static_framework = true, but
  # use_frameworks! :linkage => :static already makes all pods static.
  # Having both causes duplicate symbols at link time, so we override here.
  installer.pod_targets.each do |pod|
    if pod.name == 'CapacitorCommunityAdmob'
      def pod.static_framework?
        false
      end
    end
  end
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
