require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks! :linkage => :static

# workaround to avoid Xcode caching of Pods that requires
# temporary workaround, see https://github.com/CocoaPods/CocoaPods/issues/12226
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods

  # AppLovin MAX SDK
  pod 'AppLovinSDK'

  # Mediation adapters
  pod 'GoogleMobileAdsMediationAppLovin'   # AppLovin self-serve
  pod 'GoogleMobileAds'                    # AdMob adapter (fill rate backup)
  pod 'MintegralAdSDK'                     # Mintegral (JP/Asia high eCPM)
  pod 'UnityAds'                           # Unity Ads (game ad inventory)
  pod 'GoogleMobileAdsMediationUnity'      # Unity Ads adapter for MAX
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
